// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8baaa4b1-772e-4427-9b08-06f37066a830",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KG1er7k5z",
    "aws_user_pools_web_client_id": "ei69cn3sio9biipnaq8j7j3d1"
};


export default awsmobile;
